source("Functions/Checks.R")
source("Functions/List_func.R")
source("Functions/Factory/Importing.R")
source("Functions/Factory/Exporting.R")
source("Functions/Student/Clean_Student.R")
source("Functions/HEI/Clean_HEI.R")
source("Functions/Maintainer/Clean_Owner.R")
source("Functions/Clean_Private.R")